
    export const ADICIONAR_PROJETO = 'ADCIONAR_PROJETO'
    export const ALTERAR_PROJETO = 'ALTERAR_PROJETO'
    export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'
    export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS'

    export const NOTIFICAR = 'NOTIFICAR'

    export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS';
    export const ADICIONAR_TAREFA = "ADCIONAR_TAREFAS";
    export const ALTERA_TAREFA = 'ALTERA_TAREFA';