
    export const ADICIONAR_PROJETO = 'ADCIONAR_PROJETO'
    export const ALTERAR_PROJETO = 'ALTERAR_PROJETO'
    export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'

    export const NOTIFICAR = 'NOTIFICAR'